l_russian:
 DIVISION_QUEUED: "$N$ Един."
 DIVISIONS_QUEUED: "$N$ Единицы"
 ARMY_LEDGER_ARMIES: "Единицы"
 ARMY_LEDGER_THRESHOLD_EQUIPMENT_RATIO: "Выполненный коэффициент оснащения полевых подразделений"
 ARMY_LEDGER_THRESHOLD_BASIC_TEMPLATE_INFO: "Список шаблонов объектов"
 ARMY_LEDGER_THRESHOLD_FUZZY_TEMPLATE_COUNT: "Приблизительное количество единиц на шаблон"
 ARMY_LEDGER_THRESHOLD_TEMPLATE_COUNT: "Количество единиц шаблона"
 TRIGGER_DIVISIONS_MORE_THAN: "единицы – более $AMOUNT|H$"
 TRIGGER_DIVISIONS_LESS_THAN: "единицы – как минимум $AMOUNT|H$"
 TRIGGER_DIVISIONS: "Единицы"
 DIVISIONS: "Единицы"
 DIVISIONS_COUNTRY: "§TКоличество единицы у государства $COUNTRY|H$: $VAL|H$§!"
 ARMY_TAB: "Единицы"
 TOPBAR_ARMY_DESC: "Посмотрите обзор ваших юнитов."
 COMBAT_COMMITED_LABEL: "$COUNT$ Единицы"
 ARMY_ARMY_LABEL: "Обзор устройства"
 ARMY_DIVISONS_TAB: "§YЕдиницы§!"
 ARMY_DIVISIONS_ACTIVE: "$N$ Боевые единицы"
 ARMY_DIVISIONS_BUTTON: "§GЩелкните§!, чтобы выбрать дивизию.\n§GЩелкните§!, §Hудерживая Shift§! для выбора нескольких единиц.\n§GЩелкните правой кнопкой§!, чтобы переместить камеру к единицы."
 EXP_MULTIPLE_DIVISIONS: "$COUNT$/$TOTAL$ Единицы"
 EXP_SINGLE_DIVISION: "1 Единицы"
 VOL_MULTIPLE_DIVISIONS: "$COUNT$ Единицы"
 VOL_SINGLE_DIVISION: "1 Единицы"
 LEDGER_DIVISIONS: "Единицы"
 REQUEST_EXPEDITIONARIES_DIVISIONS_COUNT: "$NUM_DIVS|Y$ Всего единиц"
 UNITS_VIEW_DIVISIONS_COUNT: "$DIV|G$ Единицы"
 group_militia_title: "Роты ополчения"
 group_airborne_infantry_title: "Воздушно-десантные роты"
 group_airmobile_title: "Аэромобильные компании"
 group_special_forces_title: "Роты рейнджеров/специальных операций"
 group_marine_infantry_title: "Морские компании"
 group_infantry_title: "Пехотные роты"
 group_mobile_title: "Моторизированные компании"
 group_armor_title: "Механизированные/бронированные роты"
 group_combat_support_title: "Роты боевого обеспечения"