l_french:
 DIVISION_QUEUED: "$N$ Unité"
 DIVISIONS_QUEUED: "$N$ Unités"
 ARMY_LEDGER_ARMIES: "Unités"
 ARMY_LEDGER_THRESHOLD_EQUIPMENT_RATIO: "Ratio d'équipement atteint pour les unités en campagne"
 ARMY_LEDGER_THRESHOLD_BASIC_TEMPLATE_INFO: "Liste des modèles d'unités"
 ARMY_LEDGER_THRESHOLD_FUZZY_TEMPLATE_COUNT: "Nombre approximatif d'unités par modèle"
 ARMY_LEDGER_THRESHOLD_TEMPLATE_COUNT: "Nombre d'unités par modèle"
 TRIGGER_DIVISIONS_MORE_THAN: "A plus de $AMOUNT|H$ unités"
 TRIGGER_DIVISIONS_LESS_THAN: "A moins de $AMOUNT|H$ unités"
 TRIGGER_DIVISIONS: "Unités"
 DIVISIONS: "Unités"
 DIVISIONS_COUNTRY: "§T$COUNTRY|H$ : $VAL|H$ Unités§!"
 ARMY_TAB: "Unités"
 TOPBAR_ARMY_DESC: "Voir une vue d'ensemble de vos unités."
 COMBAT_COMMITED_LABEL: "$COUNT$ Unités"
 ARMY_ARMY_LABEL: "Aperçu de l'unité"
 ARMY_DIVISONS_TAB: "§YUnités§!"
 ARMY_DIVISIONS_ACTIVE: "$N$ Unités de combat"
 ARMY_DIVISIONS_BUTTON: "§GCliquer§! pour sélectionner.\n§GCliquer§! en maintenant §HShift§! pour sélectionner plusieurs unités.\n§GClic droit§! pour zoomer sur la unité."
 EXP_MULTIPLE_DIVISIONS: "$COUNT$/$TOTAL$ Unités"
 EXP_SINGLE_DIVISION: "1 Unité"
 VOL_MULTIPLE_DIVISIONS: "$COUNT$ Unités"
 VOL_SINGLE_DIVISION: "1 Unité"
 LEDGER_DIVISIONS: "Unités"
 REQUEST_EXPEDITIONARIES_DIVISIONS_COUNT: "$NUM_DIVS|Y$ Unités totales"
 UNITS_VIEW_DIVISIONS_COUNT: "$DIV|G$ Unités"
 group_militia_title: "Militia Companies"
 group_airborne_infantry_title: "Airborne Companies"
 group_airmobile_title: "Airmobile Companies"
 group_special_forces_title: "Ranger/Special Operations Companies"
 group_marine_infantry_title: "Marine Companies"
 group_infantry_title: "Infantry Companies"
 group_mobile_title: "Motorized Companies"
 group_armor_title: "Mechanized/Armored Companies"
 group_combat_support_title: "Combat Support Companies"