l_english:
 DIVISION_QUEUED: "$N$ Unit"
 DIVISIONS_QUEUED: "$N$ Units"
 ARMY_LEDGER_ARMIES: "Units"
 ARMY_LEDGER_THRESHOLD_EQUIPMENT_RATIO: "Fulfilled Equipment Ratio for Fielded Units"
 ARMY_LEDGER_THRESHOLD_BASIC_TEMPLATE_INFO: "Unit Templates List"
 ARMY_LEDGER_THRESHOLD_FUZZY_TEMPLATE_COUNT: "Approximate Per Template Unit Counts"
 ARMY_LEDGER_THRESHOLD_TEMPLATE_COUNT: "Per Template Unit Counts"
 TRIGGER_DIVISIONS_MORE_THAN: "Has more than $AMOUNT|H$ units"
 TRIGGER_DIVISIONS_LESS_THAN: "Has at least $AMOUNT|H$ units"
 TRIGGER_DIVISIONS: "Units"
 DIVISIONS: "Units"
 DIVISIONS_COUNTRY: "§T$COUNTRY|H$ has $VAL|H$ Units§!"
 ARMY_TAB: "Units"
 TOPBAR_ARMY_DESC: "See an overview of your units."

 COMBAT_COMMITED_LABEL: "$COUNT$ Units"

 ARMY_ARMY_LABEL: "Unit Overview"
 ARMY_DIVISONS_TAB: "§YUnits§!"
 ARMY_DIVISIONS_ACTIVE: "$N$ Combat Units"
 ARMY_DIVISIONS_BUTTON: "§GClick§! to select.\n§GClick§! while §HHolding Shift§! to select multiple units.\n§GRight-click§! to pan to the Unit."

 EXP_MULTIPLE_DIVISIONS: "$COUNT$/$TOTAL$ Units"
 EXP_SINGLE_DIVISION: "1 Unit"
 VOL_MULTIPLE_DIVISIONS: "$COUNT$ Units"
 VOL_SINGLE_DIVISION: "1 Unit"

 LEDGER_DIVISIONS: "Units"

 REQUEST_EXPEDITIONARIES_DIVISIONS_COUNT: "$NUM_DIVS|Y$ Total Units"
 UNITS_VIEW_DIVISIONS_COUNT: "$DIV|G$ Units"

 group_militia_title: "Militia Companies"
 group_airborne_infantry_title: "Airborne Companies"
 group_airmobile_title: "Airmobile Companies"
 group_special_forces_title: "Ranger/Special Operations Companies"
 group_marine_infantry_title: "Marine Companies"
 group_infantry_title: "Infantry Companies"
 group_mobile_title: "Motorized Companies"
 group_armor_title: "Mechanized/Armored Companies"
 group_combat_support_title: "Combat Support Companies"