l_polish:
 DIVISION_QUEUED: "$N$ Jednostka"
 DIVISIONS_QUEUED: "$N$ Jednostki"
 ARMY_LEDGER_ARMIES: "Jednostki"
 ARMY_LEDGER_THRESHOLD_EQUIPMENT_RATIO: "Spełniony współczynnik wyposażenia dla jednostek polowych"
 ARMY_LEDGER_THRESHOLD_BASIC_TEMPLATE_INFO: "Lista szablonów jednostek"
 ARMY_LEDGER_THRESHOLD_FUZZY_TEMPLATE_COUNT: "Przybliżona liczba jednostek na szablon"
 ARMY_LEDGER_THRESHOLD_TEMPLATE_COUNT: "Liczba jednostek szablonu"
 TRIGGER_DIVISIONS_MORE_THAN: "Jednostkami - więcej niż $AMOUNT|H$"
 TRIGGER_DIVISIONS_LESS_THAN: "Jednostkami - co najmniej $AMOUNT|H$."
 TRIGGER_DIVISIONS: "Jednostki"
 DIVISIONS: "Jednostki"
 DIVISIONS_COUNTRY: "§T$COUNTRY|H$ - Jednostki: $VAL|H$§!"
 ARMY_TAB: "Jednostki"
 TOPBAR_ARMY_DESC: "Zobacz przegląd swoich jednostek."
 COMBAT_COMMITED_LABEL: "$COUNT$ Jednostki"
 ARMY_ARMY_LABEL: "Przegląd jednostki"
 ARMY_DIVISONS_TAB: "§YJednostki§!"
 ARMY_DIVISIONS_ACTIVE: "$N$ Jednostki Bojowe"
 ARMY_DIVISIONS_BUTTON: "§GKliknij§!, by wybrać.\n§GKliknij§!, §Hprzytrzymując Shift§!, by wybrać więcej Jednostki.\n§GKliknij PPM§!, by wycentrować na Jednostki."
 EXP_MULTIPLE_DIVISIONS: "$COUNT$/$TOTAL$ Jednostki"
 EXP_SINGLE_DIVISION: "1 Jednostka"
 VOL_MULTIPLE_DIVISIONS: "$COUNT$ Jednostki"
 VOL_SINGLE_DIVISION: "1 Jednostka"
 LEDGER_DIVISIONS: "Jednostki"
 REQUEST_EXPEDITIONARIES_DIVISIONS_COUNT: "$NUM_DIVS|Y$ Całkowita liczba jednostek"
 UNITS_VIEW_DIVISIONS_COUNT: "$DIV|G$ Jednostki"
 group_militia_title: "Militia Companies"
 group_airborne_infantry_title: "Airborne Companies"
 group_airmobile_title: "Airmobile Companies"
 group_special_forces_title: "Ranger/Special Operations Companies"
 group_marine_infantry_title: "Marine Companies"
 group_infantry_title: "Infantry Companies"
 group_mobile_title: "Motorized Companies"
 group_armor_title: "Mechanized/Armored Companies"
 group_combat_support_title: "Combat Support Companies"