l_german:
 DIVISION_QUEUED: "$N$ Einheit"
 DIVISIONS_QUEUED: "$N$ Einheiten"
 ARMY_LEDGER_ARMIES: "Einheiten"
 ARMY_LEDGER_THRESHOLD_EQUIPMENT_RATIO: "Durchschnittliche Ausrüstungsvollständigkeit der Einheiten im Feld"
 ARMY_LEDGER_THRESHOLD_BASIC_TEMPLATE_INFO: "Liste der Einheitenvorlagen"
 ARMY_LEDGER_THRESHOLD_FUZZY_TEMPLATE_COUNT: "Ungefähre Anzahl Einheiten pro Vorlage"
 ARMY_LEDGER_THRESHOLD_TEMPLATE_COUNT: "Anzahl Einheiten pro Vorlage"
 TRIGGER_DIVISIONS_MORE_THAN: "Hat mehr als $AMOUNT|H$ Einheiten"
 TRIGGER_DIVISIONS_LESS_THAN: "Hat mindestens $AMOUNT|H$ Einheiten"
 TRIGGER_DIVISIONS: "Einheiten"
 DIVISIONS: "Einheiten"
 DIVISIONS_COUNTRY: "§T$COUNTRY|H$ hat $VAL|H$ Einheiten§!"
 ARMY_TAB: "Einheiten"
 TOPBAR_ARMY_DESC: "Siehe eine Übersicht über deine Armee."
 COMBAT_COMMITED_LABEL: "$COUNT$ Einheiten"
 ARMY_ARMY_LABEL: "Einheitenübersicht"
 ARMY_DIVISONS_TAB: "§YEinheiten§!"
 ARMY_DIVISIONS_ACTIVE: "$N$ Kampfeinheiten"
 ARMY_DIVISIONS_BUTTON: "§GKlicke§! zum auswählen.\n§GKlicke§! und §Hhalte Shift§! um mehrere Einheiten auszuwählen.\n§GRechtsklicke§! um zur Einheit zu schwenken."
 EXP_MULTIPLE_DIVISIONS: "$COUNT$/$TOTAL$ Einheiten"
 EXP_SINGLE_DIVISION: "1 Einheit"
 VOL_MULTIPLE_DIVISIONS: "$COUNT$ Einheiten"
 VOL_SINGLE_DIVISION: "1 Einheit"
 LEDGER_DIVISIONS: "Einheiten"
 REQUEST_EXPEDITIONARIES_DIVISIONS_COUNT: "$NUM_DIVS|Y$ Einheiten insgesamt"
 UNITS_VIEW_DIVISIONS_COUNT: "$DIV|G$ Einheiten"
 group_militia_title: "Milizkompanien"
 group_airborne_infantry_title: "Fallschirmjägerkompanien"
 group_airmobile_title: "Luftbewegliche Kompanien"
 group_special_forces_title: "Ranger-/Spezialeinsatzkompanien"
 group_marine_infantry_title: "Marineinfanteriekompanien"
 group_infantry_title: "Infanteriekompanien"
 group_mobile_title: "Motorisierte Kompanien"
 group_armor_title: "Mechanisierte/Panzerkompanien"
 group_combat_support_title: "Kampfunterstützungskompanien"