#!/usr/bin/env python3
"""Generate the small preview art for the main-menu background picker.

HOI4's background manager draws the "Change background" list from
common/frontend/backgrounds/*.txt, but each tile's preview comes from a sprite
named GFX_<entry>_small - never from the full-size loading screen. An entry with
no such sprite falls back to the engine's hardcoded GFX_frontend_bg_basic_small,
so a mod that ships loading screens without thumbnails shows vanilla art in the
picker next to its own backgrounds.

This writes gfx/loadingscreens/<entry>_small.dds (192x144 DXT1) for every
declared background and rewrites interface/small_background.gfx to match. Every
thumbnail is re-encoded on each run and only written when its bytes change, so
replaced art is picked up without a flag. Run it after adding a background to
common/frontend/backgrounds/.

    python3 tools/assets/generate_background_thumbnails.py
    python3 tools/assets/generate_background_thumbnails.py --check
"""

import argparse
import importlib.util
import re
import sys
import types
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install --group runtime")

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
BACKGROUNDS_DIR = Path("common/frontend/backgrounds")
LOADINGSCREENS_DIR = Path("gfx/loadingscreens")
FRONTEND_BG_GFX = Path("interface/frontendmainviewbg.gfx")
GFX_FILE = Path("interface/small_background.gfx")

THUMBNAIL_SIZE = (192, 144)

# Vanilla's small_background.gfx is the only definition of this sprite, and
# overriding that file by name replaces vanilla's copy outright, so the entry
# must be carried over. MD ships no border texture; the base game's still
# resolves under replace_path = "gfx/loadingscreens" - the reported bug (vanilla
# load_N_small.dds showing in the picker) is the proof.
BORDER_SPRITE = "GFX_frontend_loading_screen_border_small"
BORDER_TEXTURE = "gfx/loadingscreens/loading_screen_border_small.dds"

_COMMENT_RE = re.compile(r"#.*$", re.MULTILINE)
_ENTRY_RE = re.compile(r"^\s*([A-Za-z0-9_]+)\s*=\s*\{")
_FRONTEND_BG_NAME_RE = re.compile(r'name\s*=\s*"GFX_frontend_bg"')
_NAME_RE = re.compile(r"\bname\s*=")
_TEXTUREFILE_RE = re.compile(r'texture[fF]ile\s*=\s*"([^"]+)"')

_GFX_HEADER = """# Preview art for the main-menu background picker.
#
# Generated by tools/assets/generate_background_thumbnails.py - do not hand-edit.
# Overrides the vanilla file of the same name so the picker never falls back to
# base-game loading screens. The sprite names are fixed by the engine: a
# background named <x> in common/frontend/backgrounds/ reads its tile from
# GFX_<x>_small.
"""


def _load_dds_writer() -> types.ModuleType:
    """batchdds-2.py owns MD's DDS encoding; its name is not a valid module."""
    path = Path(__file__).with_name("batchdds-2.py")
    spec = importlib.util.spec_from_file_location("batchdds_2", path)
    if spec is None or spec.loader is None:
        sys.exit(f"Could not load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _read(path: Path) -> str:
    with open(path, "r", encoding="utf-8") as handle:
        return _COMMENT_RE.sub("", handle.read())


def declared_backgrounds(root: Path) -> list[str]:
    """Top-level entry names in declaration order, deduplicated."""
    names: list[str] = []
    for path in sorted((root / BACKGROUNDS_DIR).glob("*.txt")):
        depth = 0
        for line in _read(path).splitlines():
            match = _ENTRY_RE.match(line)
            if depth == 0 and match and match.group(1) not in names:
                names.append(match.group(1))
            depth += line.count("{") - line.count("}")
    return names


def menu_background(root: Path) -> Path | None:
    """The texture GFX_frontend_bg holds, which the manager lists as its own tile.

    MD points that sprite at its branded menu art instead of a loading screen, so
    the picker carries an entry no backgrounds file declares. Returns None when
    the sprite or its texturefile cannot be found.
    """
    body = _read(root / FRONTEND_BG_GFX)
    start = _FRONTEND_BG_NAME_RE.search(body)
    if start is None:
        return None
    following = _NAME_RE.search(body, start.end())
    block = body[start.end() : following.start() if following else len(body)]
    texture = _TEXTUREFILE_RE.search(block)
    return root / texture.group(1) if texture else None


def thumbnail_for(source: Path) -> Path:
    return source.with_name(f"{source.stem}_small.dds")


def render_thumbnail(dds: types.ModuleType, source: Path) -> bytes:
    with Image.open(source) as image:
        thumbnail = image.convert("RGB").resize(
            THUMBNAIL_SIZE, Image.Resampling.LANCZOS
        )
    raw = thumbnail.tobytes()
    pixels = [
        (raw[i + 2], raw[i + 1], raw[i], 255) for i in range(0, len(raw), 3)
    ]  # (b, g, r, a)
    width, height = THUMBNAIL_SIZE
    return dds.make_dxt1_header(width, height) + bytes(
        dds.compress_to_dxt1(pixels, width, height)
    )


def render_gfx(sprites: list[tuple[str, str]]) -> str:
    lines = [_GFX_HEADER, "spriteTypes = {"]
    for name, texture in [*sprites, (BORDER_SPRITE, BORDER_TEXTURE)]:
        lines.append("\tspriteType = {")
        lines.append(f'\t\tname = "{name}"')
        lines.append(f'\t\ttexturefile = "{texture}"')
        lines.append("\t}")
        lines.append("")
    lines[-1] = "}"
    return "\n".join(lines) + "\n"


def _current_bytes(path: Path) -> bytes | None:
    if not path.is_file():
        return None
    with open(path, "rb") as handle:
        return handle.read()


def main(argv: list[str] | None = None, root: Path = REPO_ROOT) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report stale or missing output without writing anything",
    )
    args = parser.parse_args(argv)

    sources = [
        (name, root / LOADINGSCREENS_DIR / f"{name}.dds")
        for name in declared_backgrounds(root)
    ]
    if not sources:
        print(f"No backgrounds declared under {BACKGROUNDS_DIR}", file=sys.stderr)
        return 1
    problems: list[str] = []
    if (root / FRONTEND_BG_GFX).is_file():
        menu = menu_background(root)
        if menu is None:
            problems.append(f"{FRONTEND_BG_GFX.as_posix()}: no GFX_frontend_bg texture")
        elif menu.stem not in {name for name, _ in sources}:
            sources.append((menu.stem, menu))

    dds = _load_dds_writer()
    sprites: list[tuple[str, str]] = []
    expected: dict[Path, bytes] = {}

    for name, source in sources:
        if not source.is_file():
            problems.append(f"{name}: no {source.relative_to(root).as_posix()}")
            continue
        try:
            rendered = render_thumbnail(dds, source)
        except (OSError, ValueError, NotImplementedError) as error:
            problems.append(f"{name}: cannot decode {source.name} ({error})")
            continue
        destination = thumbnail_for(source)
        sprites.append((f"GFX_{name}_small", destination.relative_to(root).as_posix()))
        expected[destination] = rendered

    orphans = sorted(
        path
        for path in (root / LOADINGSCREENS_DIR).glob("*_small.dds")
        if path not in expected
    )
    problems.extend(f"orphan {path.relative_to(root).as_posix()}" for path in orphans)

    gfx_path = root / GFX_FILE
    expected[gfx_path] = render_gfx(sprites).encode("utf-8")
    stale = [path for path, data in expected.items() if _current_bytes(path) != data]

    if args.check:
        problems.extend(f"stale {path.relative_to(root).as_posix()}" for path in stale)
    else:
        for path in stale:
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "wb") as handle:
                handle.write(expected[path])
        print(f"{len(stale)} file(s) written, {len(sprites)} background(s)")

    for problem in problems:
        print(problem, file=sys.stderr)
    if problems:
        print(f"{len(problems)} problem(s)", file=sys.stderr)
        return 1
    if args.check:
        print(f"{len(sprites)} background thumbnails up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
