l_korean:
 DIVISION_QUEUED: "$N$ 부대"
 DIVISIONS_QUEUED: "$N$ 부대"
 ARMY_LEDGER_ARMIES: "병력"
 ARMY_LEDGER_THRESHOLD_EQUIPMENT_RATIO: "주둔 사단의 보급된 장비 비율"
 ARMY_LEDGER_THRESHOLD_BASIC_TEMPLATE_INFO: "사단 편제 목록"
 ARMY_LEDGER_THRESHOLD_FUZZY_TEMPLATE_COUNT: "대략적인 편제당 사단 수"
 ARMY_LEDGER_THRESHOLD_TEMPLATE_COUNT: "편제당 사단 수"
 TRIGGER_DIVISIONS_MORE_THAN: "$AMOUNT|H$개 사단 초과"
 TRIGGER_DIVISIONS_LESS_THAN: "최소 $AMOUNT|H$개 사단"
 TRIGGER_DIVISIONS: "병력"
 DIVISIONS: "병력"
 DIVISIONS_COUNTRY: "§T$COUNTRY|H$ 측은 $VAL|H$개 사단 보유§!"
 ARMY_TAB: "병력"
 TOPBAR_ARMY_DESC: "사단의 개요를 봅니다."
 COMBAT_COMMITED_LABEL: "$COUNT$ 병력"
 ARMY_ARMY_LABEL: "사단 개요"
 ARMY_DIVISONS_TAB: "§Y병력§!"
 ARMY_DIVISIONS_ACTIVE: "$N$ 전투 사단"
 ARMY_DIVISIONS_BUTTON: "§G클릭§!으로 선택합니다.\n§HShift를 누른채로§! §G클릭§!해서 여러 사단을 선택합니다.\n§G우클릭§!으로 사단을 재배정 합니다."
 EXP_MULTIPLE_DIVISIONS: "$COUNT$/$TOTAL$ 사단"
 EXP_SINGLE_DIVISION: "1 병력"
 VOL_MULTIPLE_DIVISIONS: "$COUNT$ 병력"
 VOL_SINGLE_DIVISION: "1 병력"
 LEDGER_DIVISIONS: "병력"
 REQUEST_EXPEDITIONARIES_DIVISIONS_COUNT: "$NUM_DIVS|Y$ 총 사단"
 UNITS_VIEW_DIVISIONS_COUNT: "$DIV|G$ 사단"
 group_militia_title: "민병대 중대"
 group_airborne_infantry_title: "공수 중대"
 group_airmobile_title: "공중기동 중대"
 group_special_forces_title: "레인저/특수작전 중대"
 group_marine_infantry_title: "해병 중대"
 group_infantry_title: "보병 중대"
 group_mobile_title: "차량화 중대"
 group_armor_title: "기계화/기갑화 중대"
 group_combat_support_title: "전투 지원 중대"